# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import middleware_pb2 as middleware__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in middleware_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StreamMiddlewareStub(object):
    """StreamMiddleware defines bidirectional streaming for SSH chat and AI messages
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamChat = channel.stream_stream(
                '/sshchat.StreamMiddleware/StreamChat',
                request_serializer=middleware__pb2.AIResponse.SerializeToString,
                response_deserializer=middleware__pb2.ChatMessage.FromString,
                _registered_method=True)


class StreamMiddlewareServicer(object):
    """StreamMiddleware defines bidirectional streaming for SSH chat and AI messages
    """

    def StreamChat(self, request_iterator, context):
        """StreamChat establishes a bidirectional stream:
        - Server sends ChatMessage when SSH clients send messages
        - Client sends AIResponse with streaming text chunks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamMiddlewareServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamChat': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamChat,
                    request_deserializer=middleware__pb2.AIResponse.FromString,
                    response_serializer=middleware__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sshchat.StreamMiddleware', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sshchat.StreamMiddleware', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StreamMiddleware(object):
    """StreamMiddleware defines bidirectional streaming for SSH chat and AI messages
    """

    @staticmethod
    def StreamChat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/sshchat.StreamMiddleware/StreamChat',
            middleware__pb2.AIResponse.SerializeToString,
            middleware__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
