# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: middleware.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'middleware.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10middleware.proto\x12\x07sshchat\"\\\n\x0b\x43hatMessage\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x0c\n\x04nick\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\n\n\x02ip\x18\x05 \x01(\t\"\x8a\x01\n\nAIResponse\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08is_final\x18\x03 \x01(\x08\x12\x16\n\x0e\x61uth_signature\x18\x04 \x01(\x0c\x12\x16\n\x0e\x61uth_timestamp\x18\x05 \x01(\x03\x12\x0c\n\x04nick\x18\x06 \x01(\t\x12\n\n\x02ip\x18\x07 \x01(\t2Q\n\x10StreamMiddleware\x12=\n\nStreamChat\x12\x13.sshchat.AIResponse\x1a\x14.sshchat.ChatMessage\"\x00(\x01\x30\x01\x42)Z\'github.com/iwanhae/ssh-chat/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'middleware_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'github.com/iwanhae/ssh-chat/proto;proto'
  _globals['_CHATMESSAGE']._serialized_start=29
  _globals['_CHATMESSAGE']._serialized_end=121
  _globals['_AIRESPONSE']._serialized_start=124
  _globals['_AIRESPONSE']._serialized_end=262
  _globals['_STREAMMIDDLEWARE']._serialized_start=264
  _globals['_STREAMMIDDLEWARE']._serialized_end=345
# @@protoc_insertion_point(module_scope)
